clear -all

catch { analyze -sv -incdir /home/rk6650/VeriTriples/malik2627research -incdir /home/rk6650/VeriTriples/malik2627research/ip/cache -incdir /home/rk6650/VeriTriples/malik2627research/ip/phase_accumulator_clock_divider -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers/examples/a_then_b -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers/examples/counter -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers/examples/non_overlapping -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers/examples/nonconsecutive_test -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers/examples/toggling /home/rk6650/VeriTriples/malik2627research/repos_6.24/dh73_Prop-eller/synthesizable_checkers/checker_lib.vh }
catch { analyze -sv -incdir /home/rk6650/VeriTriples/malik2627research -incdir /home/rk6650/VeriTriples/malik2627research/ip/cache -incdir /home/rk6650/VeriTriples/malik2627research/ip/phase_accumulator_clock_divider -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers/examples/a_then_b -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers/examples/counter -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers/examples/non_overlapping -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers/examples/nonconsecutive_test -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers/examples/toggling /home/rk6650/VeriTriples/malik2627research/repos_6.24/dh73_Prop-eller/synthesizable_checkers/examples/a_then_b/implies_nexttime.v }

catch { analyze -sv -incdir /home/rk6650/VeriTriples/malik2627research -incdir /home/rk6650/VeriTriples/malik2627research/ip/cache -incdir /home/rk6650/VeriTriples/malik2627research/ip/phase_accumulator_clock_divider -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers/examples/a_then_b -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers/examples/counter -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers/examples/non_overlapping -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers/examples/nonconsecutive_test -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers/examples/toggling /home/rk6650/VeriTriples/malik2627research/repos_6.24/dh73_Prop-eller/synthesizable_checkers/examples/nonconsecutive_test/nonconsecutive.v }
catch { analyze -sv -incdir /home/rk6650/VeriTriples/malik2627research -incdir /home/rk6650/VeriTriples/malik2627research/ip/cache -incdir /home/rk6650/VeriTriples/malik2627research/ip/phase_accumulator_clock_divider -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers/examples/a_then_b -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers/examples/counter -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers/examples/non_overlapping -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers/examples/nonconsecutive_test -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers/examples/toggling /home/rk6650/VeriTriples/malik2627research/repos_6.24/dh73_Prop-eller/ip/cache/cache.sv }
catch { analyze -sv -incdir /home/rk6650/VeriTriples/malik2627research -incdir /home/rk6650/VeriTriples/malik2627research/ip/cache -incdir /home/rk6650/VeriTriples/malik2627research/ip/phase_accumulator_clock_divider -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers/examples/a_then_b -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers/examples/counter -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers/examples/non_overlapping -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers/examples/nonconsecutive_test -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers/examples/toggling /home/rk6650/VeriTriples/malik2627research/repos_6.24/dh73_Prop-eller/synthesizable_checkers/examples/a_then_b/athenb.v }
catch { analyze -sv -incdir /home/rk6650/VeriTriples/malik2627research -incdir /home/rk6650/VeriTriples/malik2627research/ip/cache -incdir /home/rk6650/VeriTriples/malik2627research/ip/phase_accumulator_clock_divider -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers/examples/a_then_b -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers/examples/counter -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers/examples/non_overlapping -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers/examples/nonconsecutive_test -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers/examples/toggling /home/rk6650/VeriTriples/malik2627research/repos_6.24/dh73_Prop-eller/synthesizable_checkers/examples/non_overlapping/non_overlapping.v }
catch { analyze -sv -incdir /home/rk6650/VeriTriples/malik2627research -incdir /home/rk6650/VeriTriples/malik2627research/ip/cache -incdir /home/rk6650/VeriTriples/malik2627research/ip/phase_accumulator_clock_divider -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers/examples/a_then_b -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers/examples/counter -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers/examples/non_overlapping -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers/examples/nonconsecutive_test -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers/examples/toggling /home/rk6650/VeriTriples/malik2627research/repos_6.24/dh73_Prop-eller/synthesizable_checkers/examples/toggling/toggling.v }
catch { analyze -sv -incdir /home/rk6650/VeriTriples/malik2627research -incdir /home/rk6650/VeriTriples/malik2627research/ip/cache -incdir /home/rk6650/VeriTriples/malik2627research/ip/phase_accumulator_clock_divider -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers/examples/a_then_b -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers/examples/counter -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers/examples/non_overlapping -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers/examples/nonconsecutive_test -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers/examples/toggling /home/rk6650/VeriTriples/malik2627research/repos_6.24/dh73_Prop-eller/synthesizable_checkers/examples/counter/counter.v }
catch { analyze -sv -incdir /home/rk6650/VeriTriples/malik2627research -incdir /home/rk6650/VeriTriples/malik2627research/ip/cache -incdir /home/rk6650/VeriTriples/malik2627research/ip/phase_accumulator_clock_divider -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers/examples/a_then_b -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers/examples/counter -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers/examples/non_overlapping -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers/examples/nonconsecutive_test -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers/examples/toggling /home/rk6650/VeriTriples/malik2627research/repos_6.24/dh73_Prop-eller/ip/phase_accumulator_clock_divider/phase_acc_clk_div.sv }

catch { analyze -sv -incdir /home/rk6650/VeriTriples/malik2627research -incdir /home/rk6650/VeriTriples/malik2627research/ip/cache -incdir /home/rk6650/VeriTriples/malik2627research/ip/phase_accumulator_clock_divider -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers/examples/a_then_b -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers/examples/counter -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers/examples/non_overlapping -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers/examples/nonconsecutive_test -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers/examples/toggling /home/rk6650/VeriTriples/malik2627research/repos_6.24/dh73_Prop-eller/ip/cache/cache.sv }
catch { analyze -sv -incdir /home/rk6650/VeriTriples/malik2627research -incdir /home/rk6650/VeriTriples/malik2627research/ip/cache -incdir /home/rk6650/VeriTriples/malik2627research/ip/phase_accumulator_clock_divider -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers/examples/a_then_b -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers/examples/counter -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers/examples/non_overlapping -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers/examples/nonconsecutive_test -incdir /home/rk6650/VeriTriples/malik2627research/synthesizable_checkers/examples/toggling /home/rk6650/VeriTriples/malik2627research/repos_6.24/dh73_Prop-eller/ip/phase_accumulator_clock_divider/phase_acc_clk_div.sv }


            if {[catch {elaborate -top nonconsecutive} err]} {
            puts "ELAB ERROR: $err"
            exit
            }
        
        clock -infer
        clock -list
        reset -list
        prove -all -time_limit 30s
        report -all -out jasper_runs_6.24/dh73_Prop-eller/proj_1/results.rpt
report_vacuity -out jasper_runs_6.24/dh73_Prop-eller/proj_1/vacuity.rpt
exit
