clear -all

catch { analyze -sv -incdir /home/rk6650/VeriTriples/malik2627research -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/svlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/vlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/sim/dpi -incdir /home/rk6650/VeriTriples/malik2627research/tests/lib/test_rng/test_cnt_svgen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_channel_intfs/test_consumer_lower_multilevel -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_general/test_hier_module_gen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_signals /home/rk6650/VeriTriples/malik2627research/repos_6.24/bogdanvuk_pygears/pygears/lib/vlib/skidbuffer.v }
catch { analyze -sv -incdir /home/rk6650/VeriTriples/malik2627research -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/svlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/vlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/sim/dpi -incdir /home/rk6650/VeriTriples/malik2627research/tests/lib/test_rng/test_cnt_svgen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_channel_intfs/test_consumer_lower_multilevel -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_general/test_hier_module_gen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_signals /home/rk6650/VeriTriples/malik2627research/repos_6.24/bogdanvuk_pygears/pygears/lib/vlib/sfifo.v }
catch { analyze -sv -incdir /home/rk6650/VeriTriples/malik2627research -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/svlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/vlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/sim/dpi -incdir /home/rk6650/VeriTriples/malik2627research/tests/lib/test_rng/test_cnt_svgen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_channel_intfs/test_consumer_lower_multilevel -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_general/test_hier_module_gen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_signals /home/rk6650/VeriTriples/malik2627research/repos_6.24/bogdanvuk_pygears/pygears/sim/dpi/socket_macros.svh }

catch { analyze -sv -incdir /home/rk6650/VeriTriples/malik2627research -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/svlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/vlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/sim/dpi -incdir /home/rk6650/VeriTriples/malik2627research/tests/lib/test_rng/test_cnt_svgen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_channel_intfs/test_consumer_lower_multilevel -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_general/test_hier_module_gen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_signals /home/rk6650/VeriTriples/malik2627research/repos_6.24/bogdanvuk_pygears/tests/svgen/test_general/test_hier_module_gen/hier.sv }
catch { analyze -sv -incdir /home/rk6650/VeriTriples/malik2627research -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/svlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/vlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/sim/dpi -incdir /home/rk6650/VeriTriples/malik2627research/tests/lib/test_rng/test_cnt_svgen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_channel_intfs/test_consumer_lower_multilevel -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_general/test_hier_module_gen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_signals /home/rk6650/VeriTriples/malik2627research/repos_6.24/bogdanvuk_pygears/pygears/lib/vlib/fifo.v }
catch { analyze -sv -incdir /home/rk6650/VeriTriples/malik2627research -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/svlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/vlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/sim/dpi -incdir /home/rk6650/VeriTriples/malik2627research/tests/lib/test_rng/test_cnt_svgen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_channel_intfs/test_consumer_lower_multilevel -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_general/test_hier_module_gen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_signals /home/rk6650/VeriTriples/malik2627research/repos_6.24/bogdanvuk_pygears/pygears/lib/vlib/shred.v }
catch { analyze -sv -incdir /home/rk6650/VeriTriples/malik2627research -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/svlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/vlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/sim/dpi -incdir /home/rk6650/VeriTriples/malik2627research/tests/lib/test_rng/test_cnt_svgen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_channel_intfs/test_consumer_lower_multilevel -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_general/test_hier_module_gen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_signals /home/rk6650/VeriTriples/malik2627research/repos_6.24/bogdanvuk_pygears/pygears/lib/vlib/axi_slave_write.v }
catch { analyze -sv -incdir /home/rk6650/VeriTriples/malik2627research -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/svlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/vlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/sim/dpi -incdir /home/rk6650/VeriTriples/malik2627research/tests/lib/test_rng/test_cnt_svgen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_channel_intfs/test_consumer_lower_multilevel -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_general/test_hier_module_gen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_signals /home/rk6650/VeriTriples/malik2627research/repos_6.24/bogdanvuk_pygears/tests/svgen/test_signals/bc_sig.sv }
catch { analyze -sv -incdir /home/rk6650/VeriTriples/malik2627research -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/svlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/vlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/sim/dpi -incdir /home/rk6650/VeriTriples/malik2627research/tests/lib/test_rng/test_cnt_svgen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_channel_intfs/test_consumer_lower_multilevel -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_general/test_hier_module_gen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_signals /home/rk6650/VeriTriples/malik2627research/repos_6.24/bogdanvuk_pygears/tests/svgen/test_channel_intfs/test_consumer_lower_multilevel/hier0_hier1.sv }
catch { analyze -sv -incdir /home/rk6650/VeriTriples/malik2627research -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/svlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/vlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/sim/dpi -incdir /home/rk6650/VeriTriples/malik2627research/tests/lib/test_rng/test_cnt_svgen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_channel_intfs/test_consumer_lower_multilevel -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_general/test_hier_module_gen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_signals /home/rk6650/VeriTriples/malik2627research/repos_6.24/bogdanvuk_pygears/pygears/lib/svlib/hsspy.sv }
catch { analyze -sv -incdir /home/rk6650/VeriTriples/malik2627research -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/svlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/vlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/sim/dpi -incdir /home/rk6650/VeriTriples/malik2627research/tests/lib/test_rng/test_cnt_svgen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_channel_intfs/test_consumer_lower_multilevel -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_general/test_hier_module_gen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_signals /home/rk6650/VeriTriples/malik2627research/repos_6.24/bogdanvuk_pygears/pygears/lib/vlib/sustain.v }
catch { analyze -sv -incdir /home/rk6650/VeriTriples/malik2627research -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/svlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/vlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/sim/dpi -incdir /home/rk6650/VeriTriples/malik2627research/tests/lib/test_rng/test_cnt_svgen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_channel_intfs/test_consumer_lower_multilevel -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_general/test_hier_module_gen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_signals /home/rk6650/VeriTriples/malik2627research/repos_6.24/bogdanvuk_pygears/pygears/lib/svlib/empty.sv }
catch { analyze -sv -incdir /home/rk6650/VeriTriples/malik2627research -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/svlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/vlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/sim/dpi -incdir /home/rk6650/VeriTriples/malik2627research/tests/lib/test_rng/test_cnt_svgen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_channel_intfs/test_consumer_lower_multilevel -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_general/test_hier_module_gen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_signals /home/rk6650/VeriTriples/malik2627research/repos_6.24/bogdanvuk_pygears/pygears/lib/vlib/reverse.v }
catch { analyze -sv -incdir /home/rk6650/VeriTriples/malik2627research -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/svlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/vlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/sim/dpi -incdir /home/rk6650/VeriTriples/malik2627research/tests/lib/test_rng/test_cnt_svgen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_channel_intfs/test_consumer_lower_multilevel -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_general/test_hier_module_gen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_signals /home/rk6650/VeriTriples/malik2627research/repos_6.24/bogdanvuk_pygears/tests/svgen/test_channel_intfs/test_consumer_lower_multilevel/hier0.sv }
catch { analyze -sv -incdir /home/rk6650/VeriTriples/malik2627research -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/svlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/vlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/sim/dpi -incdir /home/rk6650/VeriTriples/malik2627research/tests/lib/test_rng/test_cnt_svgen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_channel_intfs/test_consumer_lower_multilevel -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_general/test_hier_module_gen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_signals /home/rk6650/VeriTriples/malik2627research/repos_6.24/bogdanvuk_pygears/tests/lib/test_rng/test_cnt_svgen/rng_ccat.sv }
catch { analyze -sv -incdir /home/rk6650/VeriTriples/malik2627research -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/svlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/vlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/sim/dpi -incdir /home/rk6650/VeriTriples/malik2627research/tests/lib/test_rng/test_cnt_svgen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_channel_intfs/test_consumer_lower_multilevel -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_general/test_hier_module_gen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_signals /home/rk6650/VeriTriples/malik2627research/repos_6.24/bogdanvuk_pygears/pygears/lib/vlib/aximm2s.v }
catch { analyze -sv -incdir /home/rk6650/VeriTriples/malik2627research -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/svlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/vlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/sim/dpi -incdir /home/rk6650/VeriTriples/malik2627research/tests/lib/test_rng/test_cnt_svgen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_channel_intfs/test_consumer_lower_multilevel -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_general/test_hier_module_gen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_signals /home/rk6650/VeriTriples/malik2627research/repos_6.24/bogdanvuk_pygears/pygears/lib/vlib/axi_addr.v }
catch { analyze -sv -incdir /home/rk6650/VeriTriples/malik2627research -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/svlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/vlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/sim/dpi -incdir /home/rk6650/VeriTriples/malik2627research/tests/lib/test_rng/test_cnt_svgen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_channel_intfs/test_consumer_lower_multilevel -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_general/test_hier_module_gen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_signals /home/rk6650/VeriTriples/malik2627research/repos_6.24/bogdanvuk_pygears/tests/svgen/test_signals/add_sig.sv }
catch { analyze -sv -incdir /home/rk6650/VeriTriples/malik2627research -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/svlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/vlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/sim/dpi -incdir /home/rk6650/VeriTriples/malik2627research/tests/lib/test_rng/test_cnt_svgen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_channel_intfs/test_consumer_lower_multilevel -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_general/test_hier_module_gen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_signals /home/rk6650/VeriTriples/malik2627research/repos_6.24/bogdanvuk_pygears/pygears/lib/svlib/avail_spy.sv }
catch { analyze -sv -incdir /home/rk6650/VeriTriples/malik2627research -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/svlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/vlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/sim/dpi -incdir /home/rk6650/VeriTriples/malik2627research/tests/lib/test_rng/test_cnt_svgen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_channel_intfs/test_consumer_lower_multilevel -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_general/test_hier_module_gen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_signals /home/rk6650/VeriTriples/malik2627research/repos_6.24/bogdanvuk_pygears/pygears/lib/vlib/unary.v }
catch { analyze -sv -incdir /home/rk6650/VeriTriples/malik2627research -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/svlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/vlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/sim/dpi -incdir /home/rk6650/VeriTriples/malik2627research/tests/lib/test_rng/test_cnt_svgen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_channel_intfs/test_consumer_lower_multilevel -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_general/test_hier_module_gen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_signals /home/rk6650/VeriTriples/malik2627research/repos_6.24/bogdanvuk_pygears/pygears/lib/svlib/trigreg.sv }
catch { analyze -sv -incdir /home/rk6650/VeriTriples/malik2627research -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/svlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/vlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/sim/dpi -incdir /home/rk6650/VeriTriples/malik2627research/tests/lib/test_rng/test_cnt_svgen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_channel_intfs/test_consumer_lower_multilevel -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_general/test_hier_module_gen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_signals /home/rk6650/VeriTriples/malik2627research/repos_6.24/bogdanvuk_pygears/pygears/lib/vlib/axi_slave_read.v }
catch { analyze -sv -incdir /home/rk6650/VeriTriples/malik2627research -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/svlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/vlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/sim/dpi -incdir /home/rk6650/VeriTriples/malik2627research/tests/lib/test_rng/test_cnt_svgen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_channel_intfs/test_consumer_lower_multilevel -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_general/test_hier_module_gen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_signals /home/rk6650/VeriTriples/malik2627research/repos_6.24/bogdanvuk_pygears/tests/lib/test_rng/test_cnt_svgen/rng_rng.sv }
catch { analyze -sv -incdir /home/rk6650/VeriTriples/malik2627research -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/svlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/vlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/sim/dpi -incdir /home/rk6650/VeriTriples/malik2627research/tests/lib/test_rng/test_cnt_svgen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_channel_intfs/test_consumer_lower_multilevel -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_general/test_hier_module_gen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_signals /home/rk6650/VeriTriples/malik2627research/repos_6.24/bogdanvuk_pygears/pygears/lib/vlib/valve.v }
catch { analyze -sv -incdir /home/rk6650/VeriTriples/malik2627research -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/svlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/vlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/sim/dpi -incdir /home/rk6650/VeriTriples/malik2627research/tests/lib/test_rng/test_cnt_svgen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_channel_intfs/test_consumer_lower_multilevel -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_general/test_hier_module_gen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_signals /home/rk6650/VeriTriples/malik2627research/repos_6.24/bogdanvuk_pygears/pygears/lib/svlib/spy.sv }
catch { analyze -sv -incdir /home/rk6650/VeriTriples/malik2627research -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/svlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/vlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/sim/dpi -incdir /home/rk6650/VeriTriples/malik2627research/tests/lib/test_rng/test_cnt_svgen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_channel_intfs/test_consumer_lower_multilevel -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_general/test_hier_module_gen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_signals /home/rk6650/VeriTriples/malik2627research/repos_6.24/bogdanvuk_pygears/pygears/lib/vlib/axis2mm.v }
catch { analyze -sv -incdir /home/rk6650/VeriTriples/malik2627research -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/svlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/vlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/sim/dpi -incdir /home/rk6650/VeriTriples/malik2627research/tests/lib/test_rng/test_cnt_svgen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_channel_intfs/test_consumer_lower_multilevel -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_general/test_hier_module_gen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_signals /home/rk6650/VeriTriples/malik2627research/repos_6.24/bogdanvuk_pygears/tests/lib/test_rng/test_cnt_svgen/rng_hier.sv }

catch { analyze -sv -incdir /home/rk6650/VeriTriples/malik2627research -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/svlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/lib/vlib -incdir /home/rk6650/VeriTriples/malik2627research/pygears/sim/dpi -incdir /home/rk6650/VeriTriples/malik2627research/tests/lib/test_rng/test_cnt_svgen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_channel_intfs/test_consumer_lower_multilevel -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_general/test_hier_module_gen -incdir /home/rk6650/VeriTriples/malik2627research/tests/svgen/test_signals /home/rk6650/VeriTriples/malik2627research/repos_6.24/bogdanvuk_pygears/pygears/lib/vlib/skidbuffer.v }


            if {[catch {elaborate -top trigreg} err]} {
            puts "ELAB ERROR: $err"
            exit
            }
        
        clock -infer
        clock -list
        reset -list
        prove -all -time_limit 30s
        report -all -out jasper_runs_6.24/bogdanvuk_pygears/proj_0/results.rpt
report_vacuity -out jasper_runs_6.24/bogdanvuk_pygears/proj_0/vacuity.rpt
exit
